config/routes.rb
Tpe::Application.routes.draw do

  resources :users
  resources :user_sessions
  resources :photographs

  root :to => "photographs#gallery"

  match "login", :to => "user_sessions#new", :as => "login"
  match "logout", :to => "user_sessions#destroy", :as => "logout"
  
  match "registration", :to=>"users#new", :as => "registration"
  match "my/portfolio", :to=>"users#portfolio", :as => "portfolio"
  match "gallery", :to=>"photographs#gallery", :as => "gallery"
  match "photographs/view", :to=>"photographs#view", :as => "view_photograph"
  
  match "upload", :to=>"photographs#upload", :as=>"upload"
end

app/models/photograph.rb
class Photograph < ActiveRecord::Base
  belongs_to :user

  has_attached_file :photo, :styles => { :original => "800x800>", :slide => "500x500>", :gallery => "150x150#" }
  has_many :variations
  accepts_nested_attributes_for :variations, :allow_destroy=>true
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :photographs

end

app/models/user_frame_variant.rb
class UserFrameVariant < ActiveRecord::Base
end

app/models/user_print_variant.rb
class UserPrintVariant < ActiveRecord::Base

def size
  "#{self.width}X#{self.height} in #{self.finish}"
end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/models/variation.rb
class Variation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  filter_parameter_logging :password
    
  helper_method :current_user

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end
end

app/controllers/photographs_controller.rb
class PhotographsController < ApplicationController
  @logged_in_user = nil
  
  before_filter :fetch_authenticated_user, :except=>[:gallery, :show]
  
  def fetch_authenticated_user
    if current_user
      @logged_in_user=current_user
    else
      redirect_to login_path
    end
  end
  
  def upload
    @user_print_variants = UserPrintVariant.find(:all)
    @user_frame_variants = UserFrameVariant.find(:all)
    @photograph = Photograph.new(params[:photograph])
  end
  
  def create
    
    @photograph = Photograph.new(params[:photograph])
    @photograph.user_id = @logged_in_user.id
    
    if @photograph.save
      flash[:notice] = "Upload successful."
      redirect_to root_url
    else
      render :action => 'upload'
    end
  end
  
  def gallery
    @photographs = Photograph.find(:all)
  end
  
  def show
    @photograph = Photograph.find_by_id(params[:id])
  end
  
  def edit
      @photograph = Photograph.find_by_id(params[:id])
  end

  def update
    @photograph = Photograph.find_by_id(params[:id])
    
    if @photograph.update_attributes(params[:photograph])
      flash[:notice] = "Successfully updated profile."
      redirect_to portfolio_path
    else
      render :action => 'edit'
    end
  end
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Successfully logged in."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end

  def new
    @user_session = UserSession.new(params[:user_session])
  end
  
  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    flash[:notice] = "Successfully logged out."
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  @logged_in_user = nil
  
  # before_filter :fetch_authenticated_user
  
  def fetch_authenticated_user
    if current_user
      @logged_in_user=current_user
    else
      redirect_to login_path
    end
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Registration successful."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end
  
  def list
    @users=(User.find(:all)).count
  end
  
  def new
    @user = User.new(params[:user])
  end

  def edit
    @user = logged_in_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated profile."
      redirect_to root_url
    else
      render :action => 'edit'
    end
  end
  
  def portfolio
    fetch_authenticated_user
    @photographs = @logged_in_user.photographs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photographs_helper.rb
module PhotographsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tpe</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="user_nav">
	  <% if current_user %>
	    <%= link_to "Edit Profile", edit_user_path(:current) %> |
	    <%= link_to "Logout", logout_path %>
	  <% else %>
	    <%= link_to "Register", registration_path %> |
	    <%= link_to "Login", login_path %>
	  <% end %>
	</div>
<%= yield %>

</body>
</html>

app/views/photographs/_form.html.erb
<% form_for @photograph, :html => { :multipart => true } do |f| %>
  <%= render "shared/error_messages", :target=>@photograph %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </p>
	<%=select_tag :predefined_print_size, options_from_collection_for_select(@user_print_variants, :id, :size)%>
	
	<%=text_field_tag :price%>
	<input type="button" id="add" value="add"></input>
	<div id="blah">
	<%= f.fields_for :variations_attributes  do |variations_fields| %>
		<%=%>
	<%end%>
	</div>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/photographs/edit.html.erb
<%= render :partial=>'form'%>

app/views/photographs/gallery.html.erb
<% 
if @photographs 
	@photographs.each { |photograph| 
%>
	<%= link_to image_tag(photograph.photo.url(:gallery)), 
				:action => 'show', 
				:id => photograph.id 
	%>
<% 
	}
end
%>

app/views/photographs/show.html.erb
<%= image_tag @photograph.photo.url(:original) %>

app/views/photographs/upload.html.erb
<%= render :partial=>"form" %>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>  
<div id="errorExplanation">  
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>  
  <ul>  
  <% target.errors.full_messages.each do |msg| %>  
    <li><%= msg %></li>  
  <% end %>  
  </ul>  
</div>  
<% end %>

app/views/user_sessions/new.html.erb
<% form_for @user_session do |f| %>
  <%= render "shared/error_messages", :target => @user_session %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/users/_form.html.erb
<% form_for @user do |f| %>
  <%= render "shared/error_messages", :target=>@user %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/users/list.html.erb
<%= @users %>

app/views/users/new.html.erb
<%= render :partial=>'form'%>

app/views/users/portfolio.html.erb
<% @photographs.each do | photograph | %>
	<%= link_to image_tag(photograph.photo.url(:gallery)), 
		:controller=>'photographs',
		:action=>'edit',
		:id=>photograph.id
	%>
<% end %>